language: node_js
before_install:
 - if [[ `npm -v` != 3* ]]; then npm i -g npm@3.5.2; fi
 - sudo apt update
before_script:
 - npm install -g grunt-cli@1.2.0
 - sudo apt install linkchecker
script:
 - node meadowlark.js &
 - grunt
